#!/home/chengwei/anaconda/bin/python
import sys
In = open(sys.argv[1],'r')
input_line=In.readlines()
list={}
for i in input_line:
    names=i.split(';')[0].strip().split(',')
    for key1 in names:
        list.setdefault(key1,{})
        for key2 in names:
            if key1 != key2:
                if list[key1].has_key(key2)!=True:
                    list[key1][key2]=1

for i in list:
    output=i +":"
    for k in list[i]:
        output+=" "+k
    print output

    